"""Small, bounded exact checkers. Submitted code is data and is NEVER executed.

The checked assertion is generated by the checker, not copied from candidate
prose. A finite match is not a universal theorem or an optimality proof.
"""
from __future__ import annotations

import hashlib
import json
from fractions import Fraction
from itertools import permutations
from math import gcd
from time import monotonic
from typing import Annotated, Literal
import re
from pydantic import Field, TypeAdapter
from .contracts import StrictModel


class CubeCheck(StrictModel):
    kind: Literal["hypercube_paths"]
    claim_id: str
    dimension: int = Field(ge=0, le=16)
    # Vertex order in increasing label order, NOT the vector of labels per vertex.
    order: list[int] = Field(max_length=65536)
    expected_total: int = Field(ge=0)


class CubeMinimumCheck(StrictModel):
    kind: Literal["hypercube_minimum"]
    claim_id: str
    dimension: int = Field(ge=0, le=3)
    expected_minimum: int = Field(ge=0)


class PartitionCheck(StrictModel):
    # Explicit definition, NOT assumed to be the contest's undefined D_B(n).
    kind: Literal["unrestricted_partitions_allowed_parts"]
    claim_id: str
    allowed_parts: list[int] = Field(min_length=1, max_length=500)
    expected_counts: dict[str, int] = Field(min_length=1, max_length=501)


class ResidueClass(StrictModel):
    residue: int
    modulus: int = Field(ge=1, le=10**12)


class ResidueCheck(StrictModel):
    kind: Literal["residue_classes"]
    claim_id: str
    classes: list[ResidueClass] = Field(min_length=1, max_length=200)
    require_pairwise_disjoint: bool
    # If supplied, checked against gcd(modulus_i, modulus_j) for every ordered pair.
    expected_modulus_gcds: list[list[int]] | None = None


class RationalVectorCheck(StrictModel):
    kind: Literal["rational_vectors"]
    claim_id: str
    vectors: list[list[str | int]] = Field(min_length=1, max_length=100)
    require_unit_norm: bool
    max_absolute_pairwise_dot: str | int | None = None
    expected_dot_products: list[list[str | int]] | None = None


Check = Annotated[CubeCheck | CubeMinimumCheck | PartitionCheck | ResidueCheck | RationalVectorCheck,
                  Field(discriminator="kind")]
CHECKS = TypeAdapter(list[Check])


class CheckResult(StrictModel):
    kind: str
    claim_id: str
    status: Literal["MATCH", "MISMATCH", "INVALID", "INCONCLUSIVE"]
    checked_assertion: str
    scope: str
    actual: dict
    limitations: list[str]
    input_digest: str
    elapsed_seconds: float


def count_cube_paths(d: int, order: list[int]) -> tuple[int, list[int]]:
    n = 1 << d
    if len(order) != n or sorted(order) != list(range(n)):
        raise ValueError("order must be a permutation of 0..2^d-1")
    paths = [0] * n
    for v in order:
        # Unprocessed vertices have zero paths; earlier vertices have >= 1.
        paths[v] = sum(paths[v ^ (1 << bit)] for bit in range(d)) or 1
    return sum(paths), paths


def _run(check, deadline):
    if isinstance(check, RationalVectorCheck):
        def rational(value):
            text = str(value)
            if len(text) > 100 or not re.fullmatch(r"-?\d+(?:/[1-9]\d*)?", text):
                raise ValueError("Use integer or rational p/q coordinates, never floats or symbolic cosines")
            return Fraction(text)
        size = len(check.vectors[0])
        if size < 1 or size > 20 or any(len(v) != size for v in check.vectors):
            raise ValueError("Vectors must share a dimension in 1..20")
        vectors = [[rational(x) for x in v] for v in check.vectors]
        dots = [[sum((x*y for x,y in zip(a,b)), Fraction(0)) for b in vectors] for a in vectors]
        unit = all(dots[i][i] == 1 for i in range(len(vectors)))
        bound = rational(check.max_absolute_pairwise_dot) if check.max_absolute_pairwise_dot is not None else None
        if bound is not None and bound < 0:
            raise ValueError("Absolute dot-product bound must be nonnegative")
        violating = [{"i": i, "j": j, "dot": str(dots[i][j])}
                     for i in range(len(vectors)) for j in range(i+1,len(vectors))
                     if bound is not None and abs(dots[i][j]) > bound]
        expected = check.expected_dot_products
        exact_dots = True if expected is None else [[rational(x) for x in row] for row in expected] == dots
        matches = (not check.require_unit_norm or unit) and not violating and exact_dots
        return matches, {"all_unit_vectors": unit, "dot_products": [[str(x) for x in row] for row in dots],
                         "bound_violations": violating}, (
            "Checked exact rational norms and dot products for the submitted vectors."
        ), "GIVEN_CONFIGURATION", [
            "Does not prove a universal spherical-geometry bound or interpret approximations as exact coordinates.",
            "Irrational or trigonometric coordinates require a separately justified symbolic/interval calculation."]
    if isinstance(check, CubeCheck):
        total, paths = count_cube_paths(check.dimension, check.order)
        return total == check.expected_total, {
            "total_paths": total, "paths_by_vertex": paths,
        }, f"This submitted ordering of Q_{check.dimension} has {total} uphill paths.", "ONE_LABELLING", [
            "A correct witness gives an upper bound for U(Q_d), not optimality or a formula for every d."]
    if isinstance(check, CubeMinimumCheck):
        d = check.dimension
        best, witness, examined = None, None, 0
        for order in permutations(range(1 << d)):
            if examined % 256 == 0 and monotonic() > deadline:
                raise TimeoutError("Exhaustive search incomplete; no minimum certified")
            value, _ = count_cube_paths(d, list(order))
            examined += 1
            if best is None or value < best:
                best, witness = value, list(order)
        return best == check.expected_minimum, {
            "minimum": best, "witness": witness, "labellings_examined": examined,
            "search_complete": True,
        }, f"All labellings of Q_{d} were enumerated; minimum is {best}.", "FIXED_DIMENSION_EXHAUSTIVE", [
            "This proves only this finite instance, conditional on the checked counting definition and implementation."]
    if isinstance(check, PartitionCheck):
        parts = check.allowed_parts
        if any(p <= 0 or p > 500 for p in parts) or len(parts) != len(set(parts)):
            raise ValueError("allowed_parts must be distinct integers in 1..500")
        if any(not k.isdecimal() or str(int(k)) != k or int(k) > 500
               for k in check.expected_counts):
            raise ValueError("expected_counts keys must be canonical integers 0..500")
        if any(value < 0 for value in check.expected_counts.values()):
            raise ValueError("Partition counts cannot be negative")
        bound = max(map(int, check.expected_counts))
        dp = [1] + [0] * bound
        for part in sorted(parts):
            for n in range(part, bound + 1):
                dp[n] += dp[n - part]
        actual = {k: dp[int(k)] for k in check.expected_counts}
        bad = {k: {"expected": check.expected_counts[k], "actual": v}
               for k, v in actual.items() if v != check.expected_counts[k]}
        return not bad, {"counts": actual, "mismatches": bad}, (
            "Checked unordered integer partitions using only the specified positive parts, "
            "with unlimited repetitions, for the listed n."
        ), "FINITE_SAMPLE", [
            "The definition of D_B(n) was NOT supplied. This checker must not be identified with D_B without reviewing its definition.",
            "Matching finitely many values does not prove a general formula."]
    if isinstance(check, ResidueCheck):
        classes = check.classes
        matrix = [[gcd(a.modulus, b.modulus) for b in classes] for a in classes]
        intersections = []
        for i, a in enumerate(classes):
            for j in range(i + 1, len(classes)):
                b = classes[j]
                g = matrix[i][j]
                if (b.residue - a.residue) % g == 0:
                    m, q = a.modulus, b.modulus // g
                    step = 0 if q == 1 else (((b.residue - a.residue) // g) * pow(m // g, -1, q)) % q
                    witness = (a.residue + m * step) % (m * q)
                    assert (witness - a.residue) % a.modulus == 0
                    assert (witness - b.residue) % b.modulus == 0
                    intersections.append({"i": i, "j": j, "witness": witness})
        expected = check.expected_modulus_gcds
        disjoint = not intersections
        matches = (not check.require_pairwise_disjoint or disjoint) and (expected is None or expected == matrix)
        density_sum = sum((Fraction(1, c.modulus) for c in classes), Fraction(0))
        return matches, {
            "pairwise_disjoint": disjoint, "intersections": intersections,
            "modulus_gcds": matrix,
            "residue_modulus_gcds": [gcd(c.residue, c.modulus) for c in classes],
            "sum_class_densities": str(density_sum),
        }, "Checked pairwise intersections and gcds of the specified residue classes over the integers.", "GIVEN_CONFIGURATION", [
            "A configuration check does not prove a classification of all configurations.",
            "The exact problem-4 requirements were not supplied; no unstated gcd condition is assumed."]
    raise TypeError("Unsupported checker")


def run_checks(raw: list[dict], *, allowed_claim_ids: set[str], timeout_seconds: float = 10) -> list[CheckResult]:
    if len(raw) > 20:
        raise ValueError("At most 20 checks per attempt")
    checks = CHECKS.validate_python(raw, strict=True)
    deadline = monotonic() + timeout_seconds
    results = []
    for check in checks:
        if check.claim_id not in allowed_claim_ids:
            raise ValueError("Checker references an unknown candidate claim")
        start = monotonic()
        digest = hashlib.sha256(check.model_dump_json().encode()).hexdigest()
        try:
            if start > deadline:
                raise TimeoutError("Shared check budget exhausted")
            matched, actual, assertion, scope, limits = _run(check, deadline)
            status = "MATCH" if matched else "MISMATCH"
        except (ValueError, TimeoutError) as exc:
            status = "INCONCLUSIVE" if isinstance(exc, TimeoutError) else "INVALID"
            actual, assertion, scope, limits = {}, str(exc), "NOT_ESTABLISHED", ["No mathematical acceptance follows from this result."]
        results.append(CheckResult(kind=check.kind, claim_id=check.claim_id, status=status,
                                  checked_assertion=assertion, scope=scope, actual=actual,
                                  limitations=limits, input_digest=digest,
                                  elapsed_seconds=monotonic() - start))
    return results
